---
language: python
python: "3.6"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - python-pip
      - ldap-utils

install:
  - pip install -r requirements.txt

script:
  - molecule test
